### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_golovnevs#1]
Hey @golovnevs lets keep track of your app concept here.

What would you like to do for your final project?

here is an example of what another student is working on redi-js-teachers/js_sprint_2020_final_project_vidhya-eng#1

**Comment by golovnevs** [comment]
Hello, Travis! I would like to create the app which helps my wife with her blog :) My product StyleList allows users to find their basic wardrobe key pieces based on their style preferences. User goes through a quiz where she is asked to choose between 2 outfits, then the product picks 4 most frequently liked outfits and shown it to user. Then user clicks on them and the product provides list of items used on the pictures. I created a readme file with a more detailed description and uploaded screenshots. Thanks a lot for your help!

**Comment by BTBTravis** [comment]
This is an epic idea! Perfect in size for the final project. Lets build it!

**Comment by golovnevs** [comment]
Happy to hear that! Thank you!

**Comment by BTBTravis** [comment]
This issues has been solved completely by #2
